version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - mcclowes
  assignees:
  - mcclowes
  ignore:
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.1.11
    - 6.1.16
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.11
    - 6.1.15
    - 6.1.16
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.11
    - 6.1.15
    - 6.1.16
  - dependency-name: "@storybook/addon-a11y"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: next
    versions:
    - 10.0.4
    - 10.0.6
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.11
    - 6.1.15
    - 6.1.16
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.29.0
  - dependency-name: storybook
    versions:
    - 6.1.11
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
